engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- dist/*
- test/**/*
- coverage/**/*
- node_modules/**/*
